apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test-pvc
  namespace: sre-lab
spec:
  reclaimPolicy: Retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  

