apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-broken-pvc
  namespace: sre-lab
spec:
  storageClassName: non-existing-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi