apiVersion: v1
kind: Pod
metadata:
  name: frontend-client
  namespace: netpol-demo
  labels:
    app: frontend-client
    role: frontend
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.6.0
      command: ["sleep", "36000"]