apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
    component: observability
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: web