apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/application-service-alerts.yml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "application-service-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets:
              - "application-service.sre-lab.svc.cluster.local:8080"
      - job_name: "application-service-pods"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - sre-lab
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_app
            action: keep
            regex: application-service
          - source_labels:
              - __meta_kubernetes_pod_ip
              - __meta_kubernetes_pod_container_port_number
            action: replace
            regex: (.+);(.+)
            replacement: $1:$2
            target_label: __address__

          - target_label: __metrics_path__
            replacement: /actuator/prometheus

          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace

          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod

          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app

  application-service-alerts.yml: |

    groups:

      - name: application-service.rules

        rules:

          - alert: ApplicationServiceTargetDown
            expr: up{job="application-service-pods"} == 0
            for: 1m
            labels:
              severity: critical
              service: application-service
              category: availability
            annotations:
              summary: "application-service Prometheus target is down"
              description: "Prometheus cannot scrape application-service pod {{ $labels.pod }} in namespace {{ $labels.namespace }} for more than 1 minute."
              runbook: "runbooks/kubernetes-prometheus-observability-checklist.md"
          - alert: Application500Errors
            expr: sum(rate(http_server_requests_seconds_count{job="application-service-pods", status=~"5.."}[5m]))/ sum(rate(http_server_requests_seconds_count{job="application-service-pods"}[5m])) > 0.05
            for: 1m
            labels:
              severity: warning
              service: application-service
              category: errors
            annotations:
              summary: Application error rate is high
              description: The application-service pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has a 5xx error rate greater than 5% over the last 5 minutes. Please investigate the cause of the errors.
              runbook: "runbooks/kubernetes-prometheus-observability-checklist.md"