replicaCount: 2

config:
  appMode: "helm-local-values-file"
  logLevel: "INFO"

ingress:
  host: helm-app.localhost
  tls:
    secretName: app-localhost-certmanager-tls

extraEnv:
  - name: FEATURE_X_ENABLED
    value: "true"
  - name: BUSINESS_REGION
    value: "KZ"

networkPolicy:
  enabled: false
  ingress:
    enabled: true
  egress:
    enabled: false

serviceMonitor:
  enabled: false
  interval: 30s
  path: /actuator/prometheus
  labels: {}

