apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    component: observability
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "endpoints", "nodes/proxy"]
    verbs: ["get", "list", "watch"]
  