apiVersion: v1
kind: Secret
metadata:
  name: application-service-secret
  namespace: sre-lab
  labels:
    app: application-service
    component: backend
type: Opaque
stringData:
  EXTERNAL_PARTNER_API_TOKEN: local-demo-token-not-real
